version: "3.3"

services:
  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./app/sql/local.sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    links:
      - mariadb:mysql
    volumes:
      - ./app/public:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "2000:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
