version: "3.3"

services:
  mariadb:
    image: mariadb
    volumes:
      - ./app/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    volumes:
      - ./app/public:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "2000:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root


